stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: harbor.dev.socialsys.ru/happydesk/tiny-mce-editor
  DOCKER_HUB_USER: ${HARBOR_USER}
  DOCKER_HUB_PASSWORD: ${HARBOR_PASSWORD}

  
# билд и пуш докер образа
build docker image:
  stage: build
  only:
    - master
    - develop
    - /^release\/20[0-9]{6}$/
    - /^.*-test$/
    - /^release\/(.*)$/
    - /^feature\/(.*)$/
    - /^HD\-(.*)$/
  tags:
    - docker-build-runner
  script:
    - docker login -u ${DOCKER_HUB_USER} --password=${DOCKER_HUB_PASSWORD} harbor.dev.socialsys.ru
    - FULL_IMAGE_NAME=${DOCKER_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
    - echo $FULL_IMAGE_NAME
    - docker run --dns=8.8.8.8 -v $(pwd):/www -w /www --rm harbor.dev.socialsys.ru/public/node:18.17.0-alpine3.18 npm i
    - docker run --dns=8.8.8.8 -v $(pwd):/www -w /www --rm harbor.dev.socialsys.ru/public/node:18.17.0-alpine3.18 npm run build
    - docker build --pull -t ${FULL_IMAGE_NAME} --label "git.hash=$CI_COMMIT_SHA" --label "git.branch=$CI_COMMIT_BRANCH" .
    - docker push ${FULL_IMAGE_NAME}
    - docker rmi ${FULL_IMAGE_NAME}
